theme: jekyll-theme-minimal
title: LiveFlight Connect
description: LiveFlight Connect lets you control Infinite Flight from a Windows PC or a Mac. It uses the Infinite Flight Connect API, and supports interactions from joysticks and keyboards.
